### ISSUE TITLE
Interacting with other Rigid bodies and Sensors gives odd behavior

### ISSUE THREAD

**Issue by sawariz0r** [pmndrs/ecctrl#10]
Hiya! 
I'm glad to see this package. Been trying to implement it well for a long time :D

I'm running into some issues interacting with other RigidBodies and sensor-Colliders.
Here it's floating on top of the sensors. When running into one it can either bounce me up, work without any problems or just make the character stuck. 

Tabbing out and tabbing in sometimes solves this issue.

Happy to help debugging this, just flagging it.

https://github.com/pmndrs/ecctrl/assets/17275925/bb56e526-fdc2-47c9-a4a4-7455404e8968

**Comment by ErdongChen-Andrew** [comment]
Thanks @sawariz0r ! I've encountered this issue before, I thought I had fixed it 😅. The problem occurs because the downward raycasting can't properly detect the sensor collider. I'll need to find a better way to handle this.

**Comment by ErdongChen-Andrew** [comment]
@sawariz0r It has been resolved in version 1.0.33. Please give it a try, and let me know if you encounter any issues. 😁

**Comment by sawariz0r** [comment]
Works great! Thanks 🙏
