### ISSUE TITLE
How to do third person without mouse lock

### ISSUE THREAD

**Issue by lt15364967740** [pmndrs/ecctrl#14]
I can control the movement of the character, but I don't know how to change the position of the camera, and use the mouse to control the camera to rotate around the objec

**Comment by ErdongChen-Andrew** [comment]
Just to clarify, are you looking for camera control without enabling pointer lock, or would you like to know how to enable pointer lock?

**Comment by lt15364967740** [comment]
> Just to clarify, are you looking for camera control without enabling pointer lock, or would you like to know how to enable pointer lock?
I'm looking for a camera without a mouse lock

**Comment by ErdongChen-Andrew** [comment]
At the moment, it only supports pointer lock camera control. I'm thinking about adding drag control to the camera later on 🤔

**Comment by lt15364967740** [comment]
> At the moment, it only supports pointer lock camera control. I'm thinking about adding drag control to the camera later on 🤔

OK, thank you.

**Comment by ErdongChen-Andrew** [comment]
@lt15364967740 , you can now use follow cam without pointer lock (version 1.0.42)

**Comment by lklyne** [comment]
@ErdongChen-Andrew whats the process for disabling the pointer lock on a web browser? Not seeing a prop to turn it off, but it looks like its possible to unlock the mouse and only pan with drag.

**Comment by ErdongChen-Andrew** [comment]
@lklyne you can remove the `requestPointerLock` from the canvas component:
```js
<Canvas
  shadows
  /// onPointerDown={(e) => {
  ///   (e.target as HTMLCanvasElement).requestPointerLock();
  /// }}
>
```

**Comment by lklyne** [comment]
@ErdongChen-Andrew that was easy — totally overlooked that. Thank you!!
