### ISSUE TITLE
Character can't jump

### ISSUE THREAD

**Issue by GTMtremolo** [pmndrs/ecctrl#19]
My character can't jump. This is my Ground code. Please help!

import { Plane } from "@react-three/drei";
import { RapierRigidBody, RigidBody } from "@react-three/rapier";
import { useRef } from "react";

const Ground = () => {
  const ref = useRef<RapierRigidBody>(null);
  return (
    <RigidBody type="fixed" colliders="hull">
      <Plane
        position={[0, 0, 0]}
        args={[1000, 1000]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <meshStandardMaterial transparent={true} />
      </Plane>
    </RigidBody>
  );
};

**Comment by ErdongChen-Andrew** [comment]
There is not enough information provided here. Perhaps you may want to refer to the codesandbox for detailed setups:
https://codesandbox.io/p/sandbox/ecctrl-w-o-animations-3k3zxt?file=%2Fsrc%2FApp.js

**Comment by GTMtremolo** [comment]
Thank you for your response. I think the problem because the capsule stick on the floor. But I don't know how to fix it
<img width="603" alt="Screenshot 2023-11-27 at 09 32 12" src="https://github.com/pmndrs/ecctrl/assets/31275102/cdf8acd4-2526-4719-902e-f34a91416361">

**Comment by ErdongChen-Andrew** [comment]
Seems like Ecctrl is not been used. I'll need more information about the context and setup to better understand the issue.

**Comment by GTMtremolo** [comment]
I found the problem is that actualSlopeAngle always more than slopeMaxAngle therefore the capsule can't jump. But all options are default, but I don't change anything

**Comment by ErdongChen-Andrew** [comment]
Again, I need more information to be able to help 😅

**Comment by GTMtremolo** [comment]
My problem because I put the Floor component before the Ecctr component. When I reverse it, it works fine. Thank you

**Comment by adamdburton** [comment]
> My problem because I put the Floor component before the Ecctr component. When I reverse it, it works fine. Thank you

Thank you, this solved it for me.
