### ISSUE TITLE
Is there a way to reset character? 

### ISSUE THREAD

**Issue by azhong-git** [pmndrs/ecctrl#20]
For example, in context of a parkour game, when character falls off the ground, it would be nice for the parent of Ecctrl to capture the character's state (like its height) for game logic, and drive Ecctrl to reset character's position (otherwise it will be falling forever)

(Great project BTW!)

**Comment by azhong-git** [comment]
It seems I can add a check at each frame to check if character needs to be reset (see the following diff for a hard coded reset logic on character position). To make it more extensible, maybe it is worth passing a function to Ecctrl interface that takes position and return boolean to see if character needs resetting. 

If you think this can be a common issue and needs help, I can also create a PR for this. Feel free let me know.

```diff
--- a/components/canvas/ecctrl/Ecctrl.tsx
+++ b/components/canvas/ecctrl/Ecctrl.tsx
@@ -832,7 +832,12 @@ const Ecctrl = forwardRef<RapierRigidBody, EcctrlProps>(
     useFrame((state, delta) => {
       // Character current position
       if (characterRef.current) {
-        currentPos.copy(characterRef.current.translation() as THREE.Vector3);
+        const currentTranslation = characterRef.current.translation();
+        if (currentTranslation.y < -5) {
+          characterRef.current.setTranslation(new THREE.Vector3(0, 5, 0), true);
+        } else {
+          currentPos.copy(characterRef.current.translation() as THREE.Vector3);
+        }
       }
```

**Comment by ErdongChen-Andrew** [comment]
Thanks for your feedback, Andrew! 👍
Ecctrl provides a reference for users to easily reset or teleport their character. You can use the "characterRef" to translate the character's position: `<Ecctrl ref={characterRef}>`
Here is a great example of using this: https://threejs-journey.com/apps/bounce-friday/

**Comment by azhong-git** [comment]
Using "characterRef" is indeed cleaner way to go. Thank you for providing the reference. Very helpful. 

Closing this.
