### ISSUE TITLE
Having problem with character Animation Integrations

### ISSUE THREAD

**Issue by prankush-tech** [pmndrs/ecctrl#23]
HI I tried your ecctrl ,
But right now having a problem Cant Solve.

Everytime I use <EcctrlAnimation > it gives me these error even With the Demon GLB.

![image](https://github.com/pmndrs/ecctrl/assets/76916192/68ce8774-22eb-449b-ba2a-847ff0c9c175)

But works fine with removing the Animations of character
![image](https://github.com/pmndrs/ecctrl/assets/76916192/4a95a31b-547f-4154-a15c-a93fe1a83286)

![image](https://github.com/pmndrs/ecctrl/assets/76916192/d522bca8-f8e2-482a-a3aa-a2f91edf1fa7)

Please help with the issue, IS this happening for Vite.JS for React cause I am NOt using CRA.

**Comment by ErdongChen-Andrew** [comment]
These animation names are essential:
```js
const animationSet = {
idle: "Idle",
walk: "Walk",
run: "Run",
jump: "Jump_Start",
jumpIdle: "Jump_Idle",
jumpLand: "Jump_Land",
fall: "Climbing",
}
```

but you can use same animation multiple times, like so:
```js
const animationSet = {
idle: "Idle",
walk: "Walk",
run: "Run",
jump: "Jump_Start",
jumpIdle: "Jump_Start",
jumpLand: "Jump_Start",
fall: "Jump_Start",
}
```

**Comment by prankush-tech** [comment]
Ahhh, I see thanks it worked.
