### ISSUE TITLE
Character keeps endlessly floating

### ISSUE THREAD

**Issue by lighthaus205** [pmndrs/ecctrl#26]
Thanks so much for making this character control available, it's exactly what I've been looking for!

However I am having one issue, which is that the character is endlessly floating.
When applying `friction={1}` to the floor, then the Character will stop moving, but I am not sure if this is the right way to handle it, since this will also impact the walking or running speed.

Here is a codesandbox showing the issue: https://codesandbox.io/p/sandbox/test-ecctrl-mqc2t6

Appreciate any feedback!

**Comment by ErdongChen-Andrew** [comment]
Thanks, @lighthaus205 ! To resolve your issue, simply replace the plane floor with a box floor. That should do the job.

**Comment by lighthaus205** [comment]
Yes, that worked. Thanks!

**Comment by lighthaus205** [comment]
For anyone running into the same issue: The issue came back for me when adding another RigidBody to the scene. I realised the order of adding the components to the Canvas is important. Specifically, the Player / Character needs to come first. At least this fixed the bug.

Code WITHOUT Bug:

```typescript
<Physics debug timeStep="vary">
    <KeyboardControls map={keyboardMap}>
        <Ecctrl animated>
            <EcctrlAnimation
                characterURL={"/Demon.glb"}
                animationSet={animationSet}
            >
                <Demon />
            </EcctrlAnimation>
        </Ecctrl>
    </KeyboardControls>

    <RigidBody type="fixed">
        <mesh position={[0, -0.5, 0]}>
            <boxGeometry args={[20, 1, 20]} />
            <meshStandardMaterial color={"blue"} />
        </mesh>
    </RigidBody>

    <RigidBody position={[3, 0, 3]}>
        <TreeRaw />
    </RigidBody>
</Physics>
``` 



Code WITH Bug:

```typescript
<Physics debug timeStep="vary">
    <RigidBody type="fixed">
        <mesh position={[0, -0.5, 0]}>
            <boxGeometry args={[20, 1, 20]} />
            <meshStandardMaterial color={"blue"} />
        </mesh>
    </RigidBody>

    <RigidBody position={[3, 0, 3]}>
        <TreeRaw />
    </RigidBody>

    <KeyboardControls map={keyboardMap}>
        <Ecctrl animated>
            <EcctrlAnimation
                characterURL={"/Demon.glb"}
                animationSet={animationSet}
            >
                <Demon />
            </EcctrlAnimation>
        </Ecctrl>
    </KeyboardControls>
</Physics>
```

**Comment by Voidereles** [comment]
Sometimes this bug appears when you will have your character capsule too close to the surface. Try add "debug" attribute to physics for checking where your capsule is (@ErdongChen-Andrew this could be another addition to documentation)

**Comment by campbellgoe** [comment]
> Sometimes this bug appears when you will have your character capsule too close to the surface. Try add "debug" attribute to physics for checking where your capsule is (@ErdongChen-Andrew this could be another addition to documentation)

Warning: when setting debug true is removes all your props as applies its own set of defaults. So it will enable autoBalance which can cause the player to act erractically. I haven't figured out a good way other than to just manually turn autoBalance off each time I load it up and wait for the character to settle to the ground again before playing with the other values in there, although none of them stop my character from floating 2 meters off the ground. My character model origin is at has feet.

**Comment by campbellgoe** [comment]
![Screenshot 2024-05-04 084345](https://github.com/pmndrs/ecctrl/assets/17480805/d8762247-6b78-43c7-9c9f-614d4219b3f9)
Endlessly floating character.
