### ISSUE TITLE
Character animations & jump control not working

### ISSUE THREAD

**Issue by lighthaus205** [pmndrs/ecctrl#27]
Again, thanks so much for making this character control available. It's so helpful!

However, another issue I am having is that I cannot get the animations & controls to behave correctly.
When walking with the character, the animations are not getting triggered correctly. Also I can walk or run with the character, but the Jump control is not working when hitting the spacebar

Here is a codesandbox showing the issue: https://codesandbox.io/p/sandbox/test-ecctrl-mqc2t6

Appreciate any feedback!

**Comment by ErdongChen-Andrew** [comment]
Same issue, just replacing the plane floor with a box floor.

**Comment by lighthaus205** [comment]
That worked. Thanks a lot!

**Comment by lighthaus205** [comment]
For anyone running into the same issue: The issue came back for me when adding another RigidBody to the scene. I realised the order of adding the components to the Canvas is important. Specifically, the Player / Character needs to come first. At least this fixed the bug.

Code WITHOUT Bug:

```typescript
<Physics debug timeStep="vary">
    <KeyboardControls map={keyboardMap}>
        <Ecctrl animated>
            <EcctrlAnimation
                characterURL={"/Demon.glb"}
                animationSet={animationSet}
            >
                <Demon />
            </EcctrlAnimation>
        </Ecctrl>
    </KeyboardControls>

    <RigidBody type="fixed">
        <mesh position={[0, -0.5, 0]}>
            <boxGeometry args={[20, 1, 20]} />
            <meshStandardMaterial color={"blue"} />
        </mesh>
    </RigidBody>

    <RigidBody position={[3, 0, 3]}>
        <TreeRaw />
    </RigidBody>
</Physics>
``` 



Code WITH Bug:

```typescript
<Physics debug timeStep="vary">
    <RigidBody type="fixed">
        <mesh position={[0, -0.5, 0]}>
            <boxGeometry args={[20, 1, 20]} />
            <meshStandardMaterial color={"blue"} />
        </mesh>
    </RigidBody>

    <RigidBody position={[3, 0, 3]}>
        <TreeRaw />
    </RigidBody>

    <KeyboardControls map={keyboardMap}>
        <Ecctrl animated>
            <EcctrlAnimation
                characterURL={"/Demon.glb"}
                animationSet={animationSet}
            >
                <Demon />
            </EcctrlAnimation>
        </Ecctrl>
    </KeyboardControls>
</Physics>
```
