### ISSUE TITLE
Add info about animation to documentation

### ISSUE THREAD

**Issue by Voidereles** [pmndrs/ecctrl#32]
Hello!

While working on my project which uses Ecctrl I found two things with which I spent a lot of time to figure it out.

Please, if it's possible, add those to the documentation or create some FAQ:

1) Filling these animations is essential (otherwise you'll encounter errors, you can't have animations for example for only idle and walk):
const animationSet = {
  idle: "yourAnimationName",
  walk: "yourAnimationName",
  run: "yourAnimationName",
  jump: "yourAnimationName",
  jumpIdle: "yourAnimationName",
  jumpLand: "yourAnimationName",
  fall: "yourAnimationName",
}

2) If you will fill different properties of animationSet with same name of animations, those animations will play only once. 

In my case:

  const animationSet = {
    idle: 'Idle_Armature',
    walk: 'Walk_Armature',
    run: 'Falling_Armature',
    jump:'Falling_Armature',
    jumpIdle: 'Falling_Armature',
    jumpLand: 'Idle_Armature',
    fall: 'Falling_Armature',
    action1: 'Falling_Armature',
    action2: 'Falling_Armature',
    action3: 'Falling_Armature',
    action4: 'Falling_Armature',
  }
  
idleAnimation, when character is doing nothing, will play only once and then character will not play any animation, just freeze on first/last frame of the animation played.

**Comment by ErdongChen-Andrew** [comment]
Thanks @Voidereles , added a comment on the animation part.
