### ISSUE TITLE
Mobile version spins the character model when zooming in

### ISSUE THREAD

**Issue by SadmanYasar** [pmndrs/ecctrl#36]
The repo: https://github.com/SadmanYasar/portfolio_2024
Site: https://portfolio-2024-mauve.vercel.app/

On desktop it works fine but on mobile version, the model starts to shake and spins uncontrollably if I zoom in even a little bit. The configs are somewhat default except the physics timestep is set to "vary" and the plane (a boxgeometry) has ccd enabled. I have tried tweaking these settings but still the same issue. What could be causing this?

**Comment by ErdongChen-Andrew** [comment]
🤔 Not sure, your website works fine on my mobile

**Comment by SadmanYasar** [comment]
> 🤔 Not sure, your website works fine on my mobile

Tried it on another phone and it works as expected (Xiaomi Redmi Note 8 Pro). But surprised it runs smoothly on a 5 year old phone but not on a new one (Xiaomi Redmi Note 12).

Here are the demos on both phones running on same version of Chrome browser with hardware acceleration on:

Redmi Note 8 Pro:
https://github.com/pmndrs/ecctrl/assets/67522140/816248c7-984f-4838-a467-4780f4e67b57

Redmi Note 12:
https://github.com/pmndrs/ecctrl/assets/67522140/fe334c06-c117-40d3-ba0b-73a4b6e6684b

**Comment by ErdongChen-Andrew** [comment]
First time seeing this issue 😅. Maybe play with these values see if you can get a better result?

<img width="477" alt="截屏2024-03-14 16 42 47" src="https://github.com/pmndrs/ecctrl/assets/84251107/53ee4ee8-16a6-422c-bc0e-410ca187169c">

**Comment by SadmanYasar** [comment]
Closing this as I think this issue happened due to low FPS.
