### ISSUE TITLE
Can be support TransformControls?

### ISSUE THREAD

**Issue by ouronghuang** [pmndrs/ecctrl#37]
I want to use [TransformControls](https://github.com/pmndrs/drei?tab=readme-ov-file#transformcontrols)  to automatically disable the built-in controller.
But I couldn't find the corresponding parameter to control it.
If using `disableFollowCam`, the camera position will suddenly change.

**Comment by ErdongChen-Andrew** [comment]
You can setup `disableFollowCamPos` and `disableFollowCamTarget` to keep the camera position when it is disabled.

**Comment by ErdongChen-Andrew** [comment]
NP! Thank you for your PR! 👍
