### ISSUE TITLE
Can I change the followCam position?

### ISSUE THREAD

**Issue by ElkiotBear** [pmndrs/ecctrl#39]
I want to set the followCam position a little higher on the y-axis, but i have no idea how to do it. i've played with the camInitDis property but still not ideal.

**Comment by ErdongChen-Andrew** [comment]
You can set `camInitDir={{ x: 0.2, y: 0 }}` in v1.0.71. I have just fixed this feature 😅

**Comment by ElkiotBear** [comment]
Got it. Thanks for the great library! Love it!
