### ISSUE TITLE
Error with use-sync-external-store module

### ISSUE THREAD

**Issue by Romaixn** [pmndrs/ecctrl#4]
Hi! Wanted to test this package but got an error when simply import Ecctrl

`Uncaught SyntaxError: The requested module '/node_modules/.pnpm/use-sync-external-store@1.2.0_react@18.2.0/node_modules/use-sync-external-store/shim/with-selector.js?v=ed71c189' does not provide an export named 'default'`

**Comment by ErdongChen-Andrew** [comment]
You can try importing "use-sync-external-store/shim/with-selector.js" into your application. That should help resolve the problem, although I'm not entirely sure why this issue occurred. 😅

**Comment by Romaixn** [comment]
It doesn't seem to correct the problem... How would you do the import?

**Comment by ErdongChen-Andrew** [comment]
Add this: import * as withSelector from "use-sync-external-store/shim/with-selector.js", before you import Ecctrl.
You may encounter other similar issues, you can use this approach to resolve them as well.

**Comment by Romaixn** [comment]
Thanks it's work with this workaround ! 🙏🏻
