### ISSUE TITLE
Is it possible to implement this additionally for phones and tablets outside the keyboard controls?

### ISSUE THREAD

**Issue by Dukeyeboah** [pmndrs/ecctrl#45]
I have been able to implement this to my component, and it works brilliantly. I'm very grateful for this! 
I have a question though, since my current implementation works only with keyboard controls.

 <KeyboardControls map={keyboardMap}>
            <Ecctrl
              ref={playerRef}
              floatHeight={0}
              maxVelLimit={5}
              jumpVel={4}
              capsuleRadius={1}
              capsuleHalfHeight={0.01}
            >
                   <Sun />
            </Ecctrl>
          </KeyboardControls>

is there a way to implement it for phones and other touchscreen devices that don't use keyboardcontrols ? I hope my question makes sense.

**Comment by ErdongChen-Andrew** [comment]
Check the documentation `EcctrlJoystick` section: https://github.com/pmndrs/ecctrl?tab=readme-ov-file#ecctrljoystick-and-touch-buttons
You could also use your own joystick with Ecctrl.

**Comment by Dukeyeboah** [comment]
Thank you very much. Worked like a charm
