### ISSUE TITLE
Fails to work with NextJs

### ISSUE THREAD

**Issue by Magvin** [pmndrs/ecctrl#5]
- Followed Demo experience, tried to run with NextJS default configuration
Getting error `You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders` 
<img width="971" alt="image" src="https://github.com/pmndrs/ecctrl/assets/23562296/d8138ad5-25a3-46e2-a60e-3ea33cc10374">
As far I see 
<img width="400" alt="image" src="https://github.com/pmndrs/ecctrl/assets/23562296/e1339ab3-9e36-4ccd-8a5f-c79aa8d93ba6">
Ecctrl is not transpiled

Any suggestions, would be highly appreciated

**Comment by Magvin** [comment]
UPD: when i'm trying to do it via 'transpilePackages' in next.config.js in complains about three.js
<img width="962" alt="image" src="https://github.com/pmndrs/ecctrl/assets/23562296/5f12bd0a-69f2-4e27-b630-2d68bbe9771a">

**Comment by ecaii** [comment]
I had the same issue, I resolved it by adding **ecctrl** to the transpilePackages in next.config.js.

Such as `
const nextConfig = {
    transpilePackages: ['three', 'ecctrl'],
}
`

**Comment by Magvin** [comment]
tried, three complains then.
what version of Next you are using?

**Comment by ecaii** [comment]
There. 
`"ecctrl": "^1.0.25",
"next": "13.4.19",
"three": "^0.156.1",
"react": "18.2.0",
"react-dom": "18.2.0",`

What is three complaining about ?

**Comment by Magvin** [comment]
@ecaii  ah ok we are still on 13.2.4, This is issue is within nextjs`transpilePackage` they have fixed it on 13.4v.
I think easier @ErdongChen-Andrew  is just to ship dist folder fully compiled as npm module

**Comment by ErdongChen-Andrew** [comment]
Thanks @Magvin , I ended up generating different versions of the main file and publishing the dist folder. This resolved all the errors, and now everything works smoothly 😁.

**Comment by Magvin** [comment]
Legend thanks
