### ISSUE TITLE
Cannot find module 'ecctrl'" indicates that TypeScript cannot find the declaration file for the 'ecctrl' module.

### ISSUE THREAD

**Issue by golden-fruit** [pmndrs/ecctrl#54]
I recently deleted the 'node_modules' folder and reinstalled the project. However, only the 'ecctrl' library is unable to find TypeScript type declarations. Below is my 'package.json' file. I hope to receive help and welcome any suggestions.

[package.json](https://github.com/pmndrs/ecctrl/files/15124324/package.json)
![image](https://github.com/pmndrs/ecctrl/assets/70707704/332ca709-0254-4d7e-934f-ef7d9808dbe1)

**Comment by ErdongChen-Andrew** [comment]
Which version are you currently using, and what version were you using before?

**Comment by golden-fruit** [comment]
it seems like , i delete package-lock.json file case this probelm. version never change it aways is 1.0.75

**Comment by golden-fruit** [comment]
i reback to my old package-lock.json and install . it work ok now!
