### ISSUE TITLE
Optional jumpIdle is not optional

### ISSUE THREAD

**Issue by campbellgoe** [pmndrs/ecctrl#55]
on line 29 of EcctrlAnimation.tsx is this code which I think is trying to set actions[props.animationsSet.jumpIdle] but jumpIdle is optional, so the code fails if you've removed it

```
29: const action =
      actions[curAnimation ? curAnimation : props.animationSet.jumpIdle];
```

For now the solution for the user is to always specify jumpIdle in the animation set.

**Comment by ErdongChen-Andrew** [comment]
Yea, all these animations are essential. 
<img width="780" alt="截屏2024-04-28 16 45 40" src="https://github.com/pmndrs/ecctrl/assets/84251107/968b164a-4ad8-4db9-817d-58c4a1db51af">

**Comment by campbellgoe** [comment]
thanks. since i needed to remove jump I just set it to a wave animation.
