### ISSUE TITLE
Cannot read properties of undefined (reading 'reset') TypeError: Cannot read properties of undefined (reading 'reset')   

### ISSUE THREAD

**Issue by ympr-utente** [pmndrs/ecctrl#58]

**Comment by ErdongChen-Andrew** [comment]
You need to properly setup animation names:

<img width="814" alt="截屏2024-05-11 11 28 45" src="https://github.com/pmndrs/ecctrl/assets/84251107/461769a8-7b62-426e-b8fa-7e2f50dc7c3c">

**Comment by ympr-utente** [comment]
Hi, sorry I didn't realize that, also congratulations on this toolkit, thanks bro
