### ISSUE TITLE
node modules file error on 1.0.78

### ISSUE THREAD

**Issue by cyango** [pmndrs/ecctrl#59]
Upgrading to this version gives this error:

<img width="876" alt="image" src="https://github.com/pmndrs/ecctrl/assets/30806279/eda409a2-d896-4f28-9bc7-5a2eb985a623">

**Comment by ErdongChen-Andrew** [comment]
Which version were you using where this issue wasn't present?

**Comment by cyango** [comment]
1.0.77 thsi error doesn't show up. But on the newest one it shows.

**Comment by ErdongChen-Andrew** [comment]
Emm... the only difference is the ts setup. Would you mind adding this line to your tsconfig.json: `strictNullChecks: false`? Let's see if this fixes the issue.

**Comment by cyango** [comment]
That seems to fix the ecctrl side but now i get issues on other parts of the my code, but i think it's not recommended:

"Setting strictNullChecks to true is generally recommended for a few reasons:

It helps catch null and undefined errors at compile time: These are some of the most common runtime errors in JavaScript. With strictNullChecks, you can catch these errors at compile time.

It makes the code more predictable: When strictNullChecks is true, you know that a variable can't be null or undefined unless its type says it can be. This makes the code easier to reason about.

It encourages better coding practices: With strictNullChecks, you're encouraged to check for null or undefined before using a variable. This leads to safer, more robust code." - chatGPT

**Comment by cyango** [comment]
I had to refactor my code to use strictNullChecks: false. Issue solved.
