### ISSUE TITLE
Discussion: Mobile controls

### ISSUE THREAD

**Issue by Magvin** [pmndrs/ecctrl#7]
Would be nice if it won't only relay on keyboard, but also on mobile touch controls is there is a way to do this?

**Comment by Romaixn** [comment]
Yeah! Something like that for example: https://elysium.thebenezer.com/ would be awesome!

**Comment by ErdongChen-Andrew** [comment]
I'll definitely add the joystick feature in a future update 😁.

**Comment by Magvin** [comment]
I did some, but can't figure out how to do with pointer locker on mobile rotation of the world. 

https://github.com/pmndrs/ecctrl/assets/23562296/3ed86d3e-f327-4a6c-8137-23f26a847823

**Comment by ErdongChen-Andrew** [comment]
👍 That looks pretty good @Magvin ! Did you make the joystick by uself?

**Comment by Magvin** [comment]
@ErdongChen-Andrew  no. Used a library as it had directions output 
https://github.com/bobboteck/JoyStick and just added to your existing code
<img width="599" alt="image" src="https://github.com/pmndrs/ecctrl/assets/23562296/c0fe7493-9825-41d2-8e5c-c1fd34dbb614">

**Comment by ErdongChen-Andrew** [comment]
Cool! I'll definitely take a look at the repo. I'm hoping maybe drei might include a joystick in the future lol

**Comment by ErdongChen-Andrew** [comment]
@Romaixn @Magvin Ecctrl now supports touch controls. I end up making my own 3D joystick 😅

**Comment by Magvin** [comment]
What a legend !
