### ISSUE TITLE
Is there a way for the camera to follow the player's rotation (always be in his back)

### ISSUE THREAD

**Issue by NicolasBrondin** [pmndrs/ecctrl#71]
My goal is to have someone be able to play without ever touching the mouse, so the camera would always follow the player position AND rotation, I tried all the different modes but I can't find any that actually does that with a third person POV.

Did I miss something? I would love to help implementing it if needed, but for now it's hard for me to know where to start looking at in the whole code 🙂

Have a nice day!

**Comment by ErdongChen-Andrew** [comment]
Something like Coastal World? It’s not available yet, I’ll consider adding this feature. 🤔

**Comment by NicolasBrondin** [comment]
@ErdongChen-Andrew Exactly like that !

**Comment by kenil84** [comment]
I also want the same. I want to move the camera rotation by clicking on the arrow and the character should also move in that direction. Let me know if there is any cheat to do that for now.

**Comment by kenil84** [comment]
I also want the same. I want to move the camera rotation by clicking on the arrow and the character should also move in that direction. Let me know if there is any cheat to do that for now.

**Comment by metaverse1112** [comment]
I can do it right now.

**Comment by kenilvavaliya84** [comment]
Can you please share an example with me for reference? That would be a great help.
Thanks!

**Comment by kenil84** [comment]
Can you please share an example with me for reference? That would be a great help. 
Thanks!

**Comment by metaverse1112** [comment]
https://t.ly/G3ERR

**Comment by metaverse1112** [comment]
https://react-three-metaverse.vercel.app

**Comment by kenil84** [comment]
This is inspiring!
can you share the code snippet for this kind of implementation that the camera follows character.

I tried different approaches, but it doesn't worked for me.

**Comment by ErdongChen-Andrew** [comment]
Added to the Ecctrl. Try the new mode with `<Ecctrl mode="FixedCamera">`

**Comment by NicolasBrondin** [comment]
@ErdongChen-Andrew Thank you for the amazing work 🙏

Is there any possibility to set a minimum height for the camera when using FixedCamera? Otherwise the camera is always positioned horizontally to the player

**Comment by ErdongChen-Andrew** [comment]
@NicolasBrondin you can try using this prop: `camInitDir={{ x: 0.3, y: 0 }}`

**Comment by NicolasBrondin** [comment]
Same, the camera is still at the player's level as in the picture
<img width="1705" alt="Screenshot 2024-08-18 at 20 10 43" src="https://github.com/user-attachments/assets/9a48a279-d39f-4579-a506-336859950b81">

**Comment by ErdongChen-Andrew** [comment]
@NicolasBrondin What are your prop settings? Did you set a limit for the camera?

**Comment by NicolasBrondin** [comment]
@ErdongChen-Andrew For some reason, it's working now with camInitDir! I think hot reloading was messing with the prop value...

Thanks!

**Comment by TyByers21** [comment]
I'm having a problem with my character always falling through the floor no matter where I position the character or the ground. everything is setup as a trimesh in rapier.  Is anyone else having this issue?
