### ISSUE TITLE
The avatar rotates itself on the x axis on a computer with low resources

### ISSUE THREAD

**Issue by fabiansvc** [pmndrs/ecctrl#72]
With the new version of Ecctrl, does anyone have problems with the avatar on a low-resource computer? The problem I have is that when I move the avatar, it starts to rotate in the X axe without control.

https://github.com/pmndrs/ecctrl/assets/51931450/bffbe116-7dd9-43dd-a56b-e4f8ff0ce4e4

**Comment by metaverse1112** [comment]
I have had same issue.
But, I fixed this issue.

My discord username: metaverse1112

**Comment by fabiansvc** [comment]
> I have had same issue.
> But, I fixed this issue.
> 
> My discord username: metaverse1112

Thank you, I already sent you the friend request

**Comment by ErdongChen-Andrew** [comment]
You could disable the `autoBalance`

**Comment by fabiansvc** [comment]
> You could disable the `autoBalance`

Thank you so much!.
