### ISSUE TITLE
I cannot access to to the rigid body's rotation, when autoBalance is desactivated

### ISSUE THREAD

**Issue by fabiansvc** [pmndrs/ecctrl#74]
When the autoBalance is desactivated, I cannot access to the rigid body's rotation. I need this value, because I want to send the Avatar's transforms via WebSocekts. Is there a way to access to the rotation of the Ecctrl?. If I activate the autoBalance, I get an error, that is that the avatar in low hardware computer rotates without control on the X axis. 

  return (
    <Ecctrl
      ref={avatarBodyRef}
      debug={false}
      camInitDis={-1}
      camMaxDis={-1}
      camTargetPos={{ x: 0, y: 0.5, z: 0 }}
      turnSpeed={16}
      maxVelLimit={3}
      position={[0, 2, 0]}
      camMoveSpeed={2}
      autoBalance={false}
    >

**Comment by fabiansvc** [comment]
I solved yet this problem. I had to configure autoBalance={true} and  enabledRotations={[false, true, false]} in the Ecctrl. With this solution, when the computer does not have good FPS the avatar does not rotate without control on the X and Z axis.

**Comment by golden-fruit** [comment]
use this:` characterModel.getWorldQuaternion()` it works
