### ISSUE TITLE
EcctrlAnimation walking animation doesn't loop

### ISSUE THREAD

**Issue by campbellgoe** [pmndrs/ecctrl#75]
Hi,

the walking animation plays only once. often this occurs. i've got a rigged and animated 3d character .glb and am using it with EcctrlAnimation.

Any idea why walking animation gets stuck and stops looping? sometimes it works fine,

**Comment by ErdongChen-Andrew** [comment]
How did you set up the `animationSet`?

**Comment by campbellgoe** [comment]
const animationSet = {
    idle: 'Idel',
    walk: 'Walking',
    run: 'running',
    jump: 'Walking',
    jumpIdle: 'Walking',
    jumpLand: 'Walking',
    fall: 'Idel',
    action1: 'Talking',
    action2: 'Talking 2',
  }
  
  This is the name of the actions that they gave me for this animated character.

**Comment by campbellgoe** [comment]
Note jump is disabled with jumpVel={0} I believe.

**Comment by ErdongChen-Andrew** [comment]
Try this, setting these to Idle: 
`{jump: 'Idel',
jumpIdle: 'Idel',
jumpLand: 'Idel'}`

**Comment by campbellgoe** [comment]
Thanks, that resolved the issue.
