### ISSUE TITLE
Get the position of ecctrl on each Frame

### ISSUE THREAD

**Issue by PratikPatel-113** [pmndrs/ecctrl#78]
I am trying to implement a proximity kind of thing, where a character is about to reache near some 3D mesh or node at that particular time, the audio starts playing while comparing the distance between character and that particular node.

How can i get the position at each particular frame of the ecctrl controller?

**Comment by ErdongChen-Andrew** [comment]
Give ecctrl a ref, and track it's translation: `ecctrlRef.current.translation()`

**Comment by PratikPatel-113** [comment]
I tried using the ref, but it returns the translation value only once, when it is mounted into the scene. I need the value of translation on each frame for comparison.

**Comment by ErdongChen-Andrew** [comment]
Did you put it in the useFrame loop?

**Comment by PratikPatel-113** [comment]
yes, obviously!

**Comment by PratikPatel-113** [comment]
Here is my code snippet.

`useEffect(() => {
        console.log("Connecting", controllerRef?.current?.translation());
        console.log("Connecting City", cityRef?.current?.position);

    }, [controllerRef, cityRef, controllerRef?.current, cityRef?.current])`

`<KeyboardControls map={keyboardMap}>
                            <Controller
                                maxVelLimit={5}
                                camMaxDis={-5}
                                camMinDis={-5}
                                mode="FixedCamera"
                                camCollision={false}
                                autoBalance={true}
                                enabledRotations={[false, true, false]}
                                ref={controllerRef}
                            >
                                <RigidBody
                                    ref={cubeRef}
                                    colliders="hull"
                                    restitution={0.01}
                                    friction={1}
                                    position={[0, 0, 0]}
                                    onCollisionEnter={handleCollision}
                                    type="fixed"
                                >
                                    <Character
                                        modelPath="../assets/glbs/character.glb"
                                        scale={0.01}
                                        position={[0, -1.5, 0]}
                                    />
                                </RigidBody>
                            </Controller>
                        </KeyboardControls>`

**Comment by ErdongChen-Andrew** [comment]
You need useFrame:
```js
 useFrame(() => {
    if (ecctrlRef.current ) {
      console.log(ecctrlRef.current.translation());
    }
  });
```

**Comment by ErdongChen-Andrew** [comment]
Apply the ref to your ecctrl tag: `<Ecctrl ref={ecctrlRef}>`

**Comment by PratikPatel-113** [comment]
Thanks, this worked for me.

**Comment by PratikPatel-113** [comment]
Thank you for your support.
