### ISSUE TITLE
Character is sliding automatically

### ISSUE THREAD

**Issue by kenil84** [pmndrs/ecctrl#81]
I have one character in which, I am moving the character using left right forward, and backwards. I am using `mode="FixedCamera"`. But when I am clicking on forward the character is sliding automatically.

**Comment by NicolasBrondin** [comment]
Had the same issue going from 1.0.79 working great, to 1.0.81 with the following issues :
- Character infinitely sliding on the floor
- Animations not triggering

**Comment by ErdongChen-Andrew** [comment]
Check the version of `@react-three/rapier`; it needs to be higher than `1.4.0`

**Comment by kenil84** [comment]
@ErdongChen-Andrew It is working fine after changing the version of the library. Thanks for your help.
