### ISSUE TITLE
版本：1.0.88：ecctrl 组件的mode设置无效，始终为FixedCamera 模式

### ISSUE THREAD

**Issue by golden-fruit** [pmndrs/ecctrl#90]
版本：1.0.88：ecctrl 组件的mode设置无效，始终为FixedCamera 模式

**Comment by ErdongChen-Andrew** [comment]
这边测试没发现问题

**Comment by golden-fruit** [comment]
这是我的设置：  <Ecctrl
autoBalance={false}
      camInitDis={-0.01}
      mode="CameraBasedMovement"
      name="player"
    >

**Comment by ErdongChen-Andrew** [comment]
<img width="850" alt="截屏2024-08-15 18 41 00" src="https://github.com/user-attachments/assets/700d4133-752d-4956-82e9-70ff88130733">
第一人称用的就是`camInitDis={-0.01}`，没发现有问题
有设置`dubug` 吗，建议关掉再做测试

**Comment by golden-fruit** [comment]
原来的左右移动不会旋转镜头，现在左右移动时，即使我设置了  mode="CameraBasedMovement" 也会出现镜头的旋转，这是正常的吗

**Comment by ErdongChen-Andrew** [comment]
这边没有发现问题，需要提供下完整的配置代码，最好有视频演示

**Comment by golden-fruit** [comment]
`<Ecctrl
      camListenerTarget="document"
      autoBalance={false}
      position={[0, 7, 0]}
      floatHeight={0.01}
      camInitDis={-0.01}
      camMinDis={-0.01}
      camMaxDis={-0.01}
      camFollowMult={100}
      turnVelMultiplier={1}
      turnSpeed={100}
      mode="CameraBasedMovement"
      name="player"
    >`
![Uploading ezgif-2-fcbdc7c19d.gif…]()

**Comment by golden-fruit** [comment]
![ezgif-2-fcbdc7c19d](https://github.com/user-attachments/assets/d814a417-6b70-4359-9ab7-80e3cbfe0761)

**Comment by golden-fruit** [comment]
![ezgif-6-e1d521d0a8](https://github.com/user-attachments/assets/7d7cc43e-bb2a-4193-93de-404a32e03267)

**Comment by ErdongChen-Andrew** [comment]
加一个：camLerpMult={1000}

**Comment by golden-fruit** [comment]
完美解决问题，但是我想知道这是为什么

**Comment by ErdongChen-Andrew** [comment]
新加的camera lerp功能，第一人称要单独设置
