### ISSUE TITLE
当我使用第一人称视角，并且想让相机移动具有动画效果如何设置

### ISSUE THREAD

**Issue by golden-fruit** [pmndrs/ecctrl#95]
这是我的代码```

export default function Player() {

  const rigidRef = useRef<RapierRigidBody>(null); //  玩家所在刚体
  const [disable, setDisable] = useState(false);

  useEffect(() => {
    setTimeout(() => {
      console.log("rigidRef", rigidRef);
      setDisable(true);
    }, 5000);
  }, []);

  return (
    <Ecctrl
      disableFollowCam={disable}
      disableFollowCamPos={{ x: 5, y: 2, z: 5 }}
      disableFollowCamTarget={{ x: 6, y: 0, z: 6 }}

      camCollision={false}
      camInitDis={-0.01}
      camMinDis={-0.01}
      camMaxDis={-0.01}
      camLerpMult={1000}
      camFollowMult={1000}
      turnVelMultiplier={1}
      turnSpeed={100}
      mode="CameraBasedMovement"
      name="player"
      ref={rigidRef}
    />
  );
}
``` 当我设置`disableFollowCam `为 `true`时, 相机立刻切换过去了，这里我能够插值变化吗，比如让`disableFollowCamPos`等于一个引用值，然后插值改变它。

**Comment by ErdongChen-Andrew** [comment]
试试最新的版本，disableFollowCam之后相机会停留原来的位置
