### ISSUE TITLE
Thoughts about Rapier's builtin Character controller

### ISSUE THREAD

**Issue by hichemfantar** [pmndrs/ecctrl#98]
I just discovered that Rapier has an existing implementation for character control https://rapier.rs/docs/user_guides/javascript/character_controller

what do you think about using it for this project?

**Comment by ErdongChen-Andrew** [comment]
I don't think that is rigibody controller

**Comment by hichemfantar** [comment]
> I don't think that is rigibody controller

what do you think of these rigid body references

![image](https://github.com/user-attachments/assets/3c0585e9-048e-4c91-9183-b478fff7c5f7)

**Comment by ErdongChen-Andrew** [comment]
That’s a kinematic body, not a force-based rigid body. 
If you prefer the default controller, you can follow this site:
https://sketches.isaacmason.com/sketch/rapier/kinematic-character-controller
