### ISSUE TITLE
bug: rerender causes leak for shot cubes

### ISSUE THREAD

**Issue by hichemfantar** [pmndrs/ecctrl#99]
https://github.com/user-attachments/assets/63b9d359-a042-460f-91c5-eb8e32f00bb6

1. open example project
2. left mouse click to shoot cube
3. save shotcube.tsx to cause hmr
4. left mouse click to shoot again
5. 2 cubes spawn instead of one
6. save again
7. shoot again
8. 3 cubes spawn etc

**Comment by ErdongChen-Andrew** [comment]
Refresh the browser after making code changes

**Comment by hichemfantar** [comment]
I'm aware of the refresh workaround, however i was thinking of a fix for the leak and probably getting rid of the useState for the cubes and rendering them imperatively should solve the issue i believe.

**Comment by ErdongChen-Andrew** [comment]
That’s just an example, you can improve it however you like in your app. Another improvement could be using instanced cubes

**Comment by hichemfantar** [comment]
thanks for the idea, i'm just trying to see what we can do to include good practices as many people will probably use the example as a starting point.

**Comment by hichemfantar** [comment]
@ErdongChen-Andrew turns out the issue was an incorrect function reference in the event listener
